spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud?userSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/tomorrow/mapper/xml/*.xml
  type-aliases-package: com.tomorrow.pojo
